const QUOTATION_ROLES = ["sales", "finance_director", "general_manager"];
const getUsers = (env) => JSON.parse(env.MNT_USERS_JSON || "[]");
const encode = (value) => btoa(unescape(encodeURIComponent(value))).replace(/=/g, "").replace(/\+/g, "-").replace(/\//g, "_");
const decode = (value) => decodeURIComponent(escape(atob(value.replace(/-/g, "+").replace(/_/g, "/") + "===".slice((value.length + 3) % 4))));
async function sign(value, secret) { const key = await crypto.subtle.importKey("raw", new TextEncoder().encode(secret), { name: "HMAC", hash: "SHA-256" }, false, ["sign"]); const bytes = new Uint8Array(await crypto.subtle.sign("HMAC", key, new TextEncoder().encode(value))); return btoa(String.fromCharCode(...bytes)).replace(/=/g, "").replace(/\+/g, "-").replace(/\//g, "_"); }
async function tokenFor(user, env) { const body = encode(JSON.stringify({ id: user.id, exp: Date.now() + 43200000 })); return `${body}.${await sign(body, env.AUTH_SECRET)}`; }
async function authenticate(request, env) { const token = (request.headers.get("authorization") || "").replace(/^Bearer\s+/i, ""); const [body, supplied] = token.split("."); if (!body || !supplied || !env.AUTH_SECRET || await sign(body, env.AUTH_SECRET) !== supplied) return null; try { const payload = JSON.parse(decode(body)); return payload.exp >= Date.now() ? getUsers(env).find((u) => u.id === payload.id) || null : null; } catch { return null; } }
const safePart = (value) => /^[a-zA-Z0-9_-]{1,80}$/.test(value || "") ? value : null;
async function login(request, env) { if (!env.AUTH_SECRET || !env.MNT_USERS_JSON) return new Response("登录服务未配置", { status: 503 }); let input; try { input = await request.json(); } catch { return new Response("请求无效", { status: 400 }); } const user = getUsers(env).find((u) => u.id === input.id && u.password === input.password); if (!user) return new Response("账号或密码不正确", { status: 401 }); const { password, ...safeUser } = user; return Response.json({ token: await tokenFor(user, env), user: safeUser }, { headers: { "cache-control": "no-store" } }); }
async function files(request, env, url) { const user = await authenticate(request, env); if (!user) return new Response("账号验证失败", { status: 401 }); const orderId = safePart(url.searchParams.get("orderId")); const category = safePart(url.searchParams.get("category")); if (!orderId || !["logo", "appearance", "quotation"].includes(category)) return new Response("附件参数无效", { status: 400 }); if (category === "quotation" && !QUOTATION_ROLES.includes(user.role)) return new Response("当前账号无权查看报价文件", { status: 403 }); const key = `${orderId}/${category}`; if (request.method === "DELETE") { if (user.role !== "sales") return new Response("只有销售可以删除附件", { status: 403 }); await env.FILES.delete(key); return Response.json({ ok: true }); } if (request.method === "POST") { let name = request.headers.get("x-file-name") || "attachment"; try { name = decodeURIComponent(name); } catch {} const data = await request.arrayBuffer(); await env.FILES.put(key, data, { metadata: { name, type: request.headers.get("content-type") || "application/octet-stream", uploadedBy: user.id } }); return Response.json({ ok: true, name }); } if (request.method === "GET") { const object = await env.FILES.getWithMetadata(key, { type: "arrayBuffer" }); if (!object?.value) return new Response("附件不存在", { status: 404 }); return new Response(object.value, { headers: { "content-type": object.metadata?.type || "application/octet-stream", "content-disposition": `attachment; filename*=UTF-8''${encodeURIComponent(object.metadata?.name || "attachment")}` } }); } return new Response("Method not allowed", { status: 405 }); }
export default { async fetch(request, env) { const url = new URL(request.url); if (url.pathname === "/api/login" && request.method === "POST") return login(request, env); if (url.pathname === "/api/files") return files(request, env, url); return env.ASSETS.fetch(request); } };
